version: "3"
services:
  selenium:
    image: selenium/standalone-chrome:latest
    ports:
      - "4444:4444"
    privileged: true
    shm_size: 2g
  app:
    build: 
      context: ./project
      dockerfile: Dockerfile
    volumes:
      - ./project:/usr/src/app
    expose:
      - 5000
    ports:
      - "8080:5000"
    depends_on: 
      - selenium
